### ISSUE TITLE
It seems that this document is not very clear and messy. How to install and use this tool? Can you write it in detail

### ISSUE THREAD

**Issue by pengzhengfa** [znsio/perfiz#9]
It seems that this document is not very clear and messy. How to install and use this tool? Can you write it in detail

**Comment by harikrishnan83** [comment]
Thanks for reporting the issue @pengzhengfa

Installation instructions are [here](https://github.com/znsio/perfiz#installation)
Tutorials to help you get started are [here](https://github.com/znsio/perfiz#tutorials-and-exercises).

Please elaborate which part of the documentation is not clear so that we can make necessary changes.

**Comment by pengzhengfa** [comment]
This document doesn't make it clear how to integrate with the grafana tool

**Comment by harikrishnan83** [comment]
Not sure I understand what you mean by "integrate with Grafana". Perfiz includes Dockerised Grafana which is pre-configured to talk to Dockerised Prometheus and Influx. If you have not already tried, I recommend you try this [demo](https://github.com/znsio/perfiz-demo) to get a better picture.

**Comment by pengzhengfa** [comment]
![image](https://user-images.githubusercontent.com/33858082/124406673-91621080-dd74-11eb-964c-d9d896bf5849.png)
With $perfiz_ The home / perfiz.sh start command can't pull the image down

**Comment by harikrishnan83** [comment]
hello @pengzhengfa , thanks for sharing the screenshot. This can happen when the images may be taking longer than expected to download. Please check if you need to make any changes to your Docker setup like setting up a mirror etc.

BTW since this issue is unrelated the documentation problem, can you please log it as a separate item?

**Comment by pengzhengfa** [comment]
![image](https://user-images.githubusercontent.com/33858082/124554189-475a5700-de68-11eb-83ee-a0405b9a687e.png)

**Comment by pengzhengfa** [comment]
This tool can't be used at all. I don't know how you open source it

**Comment by harikrishnan83** [comment]
Kindly report issues not related to this thread as separates issues and please adhere to the latest issue reporting template.

**Comment by harikrishnan83** [comment]
Closing this issue because there has been no response to our request for more information on the original documentation problem. Please reach out if you have or find the answers we need so that we can investigate further.
